# Generated by Django 5.1.7 on 2025-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings_email_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gallery_style',
            field=models.CharField(choices=[('grid', 'Grid Layout'), ('slider', 'Slider Gallery'), ('masonry', 'Masonry Grid')], default='grid', max_length=10),
        ),
    ]
