# Generated by Django 5.1.7 on 2025-04-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_category_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cover_image',
        ),
    ]
